[project]
name = 'Decentralized-Intellectual-Property-Licensing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.compliance-monitoring]
path = 'contracts/compliance-monitoring.clar'
clarity_version = 2
epoch = 2.5

[contracts.ip-registration]
path = 'contracts/ip-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
